version: 2.1
executors:
  exectr:
    docker:
      - image: silverlinings89/cpp_build_environment:latest
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            cmake -S . -B build/
      - persist_to_workspace:
          root: .
          paths: build
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd build
            ./*_tst --gtest_output=xml
      - store_test_results:
          path: buildworkflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
