version: 2.1
executors:
  exectr:
    docker:
      - image: johnstsimoes/cpp-ready:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            cmake -S . -B build/
            cmake --build build/
      - persist_to_workspace:
          root: .
          paths: build
  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            redis-server --daemonize yes
            cd build/tests
            ./build/tests/unit/libstein_unit --gtest_output=xml
      - store_test_results:
          path: build/tests
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
